create table groups (
	id number generated by default on null as identity primary key,
	name varchar2(64) not null, 
	c_val number default 0 not null
);
create table students (
	id number generated by default on null as identity primary key, 
	name varchar2(64) not null, 
	group_id number references groups (id) on delete cascade
);
create table exams (
	id number generated by default on null as identity primary key,
	name varchar2(64) not null,
	date_and_time timestamp with local time zone not null,
	group_id number references groups (id) on delete cascade
);
